spring.application.name=backend-api
spring.datasource.url=jdbc:postgresql://localhost:5432/infirmeriedb
spring.datasource.username=postgres
spring.datasource.password=ashanti
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
# server.servlet.context-path=/api
spring.docker.compose.enabled=false
spring.jpa.open-in-view=false
jwt.secret=aW5maXJtZXJpZV9zb2ZpdGV4X3NlY3JldF9rZXlfMjAyNV9ib2Jv
jwt.expiration=86400000




